### ISSUE TITLE
additional maintainers

### ISSUE THREAD

**Issue by pmav99** [conda-forge/searvey-feedstock#9]
@SorooshMani-NOAA would you mind if I added you as a maintainer in searvey-feedstock?

**Comment by SorooshMani-NOAA** [comment]
@pmav99 sure, no problem, please add me as well. I'm not very familiar with the feedstock maintenance. Is there anything I need to update for every release after releasing on the main dev repo?

**Comment by pmav99** [comment]
I am not particularly familiar with conda packaging either. 

The general idea is that every time we create a tag (or maybe github release?) in searvey a new PR is automatically made in the current repo. If there are no major changes in the package (e.g. no new dependencies etc), then usually just merging the PR is enough.

If there are changes, then we may need to add additional commits on top of the automatically created ones. Each time you push a commit in the PR, the CI runs and builds the package. The fact that the package is being built, does not necessarily mean that the package is OK, too, so you need to test the package, too.

Anyhow, maintaining python packages on conda it is not anything too complicated, just (as everything else related with CI) potentially time consuming.

**Comment by pmav99** [comment]
Just to give you an example of the workflow:

when you released searvey 0.3.2, this PR was created: https://github.com/conda-forge/searvey-feedstock/pull/6

The automatically created PR usually only contains some metadata updates: https://github.com/conda-forge/searvey-feedstock/pull/6/commits/ef60f9e0493f0dccbb6051eedcfe22fa2c81e7c4

If you read the first post of the PR, you will notice though that we got a warning for some packages (typepigeon and typing_extensions). The warning was correct, so I pushed an extra commit in the PR to take care of that: https://github.com/conda-forge/searvey-feedstock/pull/6/commits/5298044314ae9db0a911d12ebb7993ca63f1f96c 

After that, since the package was built correctly I merged the PR, and the CI released `pyhd8ed1ab_0`. When I tested the package though, I was getting a traceback. I investigated that in https://github.com/conda-forge/searvey-feedstock/issues/7

The issue was an upstream one and it got resolved by the `dataretrieval` maintainers, but in order to make sure that our package always pulls the correct version of dataretrieval, I made a new PR which added an extra constraint: https://github.com/conda-forge/searvey-feedstock/pull/8 After merging CI published `pyhd8ed1ab_1`. I tested the package again and it was working fine.

Nevertheless, just in order to avoid similar issues in the future, I made another PR which added some automated tests for the API https://github.com/conda-forge/searvey-feedstock/pull/10. After merging CI published `pyhd8ed1ab_2`.

So now there are 3 builds for searvey 0.3.2.

For the record, this is the most complicated work I've done in conda. Usually it is quite simpler

**Comment by pmav99** [comment]
@conda-forge-admin, please add user @SorooshMani-NOAA

**Comment by pmav99** [comment]
Hmm... according to [this](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username) issue #11 should make a PR which would add you as a maintainer. It doesn't work though. @brey any ideas?

**Comment by brey** [comment]
I don't think it's automatic. Give it some time.

**Comment by pmav99** [comment]
From the wording, I would expect that it was automatic. Anyhow, no real hurry here.

**Comment by brey** [comment]
I have posted a question on Gitter and this was the response:

> I think this is a bug in the bot that has been plaguing us lately. Could you try editing the issue? What you change doesn't seem to be important, but people had luck with removing the comma in the title.

Removing the comma worked.

**Comment by brey** [comment]
Next time we need to change the README to add Soroosh. I leave the issue open as a reminder.

**Comment by brey** [comment]
Apparently there was an issue with the PR and I have missed it.

**Comment by brey** [comment]
CODEOWNERS errors

> Unknown owner on line 1: make sure @SorooshMani-NOAA exists and has write access to the repository
* @SorooshMani-NOAA @brey @pmav99 @zacharyburnett

**Comment by brey** [comment]
@SorooshMani-NOAA Do you have a pending invite for becoming a maintainer of `searvey` feedstock?

**Comment by SorooshMani-NOAA** [comment]
@brey I just noticed an invite to join @conda-forge and accepted it. Thanks for following up.

**Comment by brey** [comment]
Now Soroosh is listed [here](https://github.com/orgs/conda-forge/teams/searvey) as well. I expect that next time the README will be updated as well. Closing for now.
